version: '3'

services:
  php:
    image: php:8.0-fpm-alpine
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./backend/:/var/www/html
  nginx:
    image: nginx:1-alpine
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build/:/usr/share/nginx/html
    links:
      - php
#  frontend:
#    image: node:14-alpine
#    ports:
#      - 8000:3000
#    volumes:
#      - ./frontend/:/home/node
#    command: sh -c "cd /home/node && yarn start"
#    links:
#      - nginx